import { OWNERS } from '@/lib/documents/owners';

import type { AuditEvent } from './types';

const now = Date.now();
const hours = (n: number) => new Date(now - n * 60 * 60 * 1000).toISOString();
const days = (n: number) => new Date(now - n * 24 * 60 * 60 * 1000).toISOString();

function user(id: keyof typeof OWNERS) {
  const owner = OWNERS[id];
  return {
    userId: owner.id,
    userName: owner.name,
    userInitials: owner.initials,
    userAvatarColor: owner.avatarColor,
  };
}

export const SEED_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'audit-1',
    timestamp: hours(2),
    ...user('user-sarah-chen'),
    action: 'Created Version v4.0',
    actionType: 'document.version',
    resourceType: 'document',
    resourceId: 'doc-1',
    resourceLabel: 'Master_Services_Agreement.pdf',
    ip: '192.168.1.45',
    location: 'London, UK',
    severity: 'success',
    metadata: { version: '4.0' },
  },
  {
    id: 'audit-2',
    timestamp: hours(5),
    ...user('user-james-doe'),
    action: 'Permission Update',
    actionType: 'permission.update',
    resourceType: 'role',
    resourceId: 'role-editor',
    resourceLabel: 'Project_Zephyr_Legal',
    ip: '10.0.0.12',
    location: 'New York, US',
    severity: 'warning',
  },
  {
    id: 'audit-3',
    timestamp: hours(8),
    userId: 'system',
    userName: 'System Automator',
    userInitials: 'SA',
    userAvatarColor: '#6b7280',
    action: 'Mass Deletion Attempt',
    actionType: 'document.delete_attempt',
    resourceType: 'multiple',
    resourceId: 'bulk-14',
    resourceLabel: 'Multiple (14 Items)',
    resourceCount: 14,
    ip: '172.16.0.88',
    location: 'Unknown',
    severity: 'critical',
  },
  {
    id: 'audit-4',
    timestamp: hours(12),
    ...user('user-maria-rodriguez'),
    action: 'New Upload',
    actionType: 'document.upload',
    resourceType: 'document',
    resourceId: 'doc-3',
    resourceLabel: 'NDA_Tesla_Motors_Final.pdf',
    ip: '192.168.1.78',
    location: 'San Francisco, US',
    severity: 'success',
  },
  {
    id: 'audit-5',
    timestamp: days(1),
    ...user('user-james-doe'),
    action: 'Approved',
    actionType: 'document.approve',
    resourceType: 'document',
    resourceId: 'doc-1',
    resourceLabel: 'Corporate Risk Assessment 2023',
    ip: '192.168.1.45',
    location: 'London, UK',
    severity: 'success',
  },
  {
    id: 'audit-6',
    timestamp: days(1),
    ...user('user-sarah-chen'),
    action: 'Rejected',
    actionType: 'document.reject',
    resourceType: 'document',
    resourceId: 'doc-2',
    resourceLabel: 'Finance Quarterly Audit Q3',
    ip: '10.0.0.22',
    location: 'Chicago, US',
    severity: 'warning',
  },
  {
    id: 'audit-7',
    timestamp: days(2),
    ...user('user-admin'),
    action: 'Folder Created',
    actionType: 'folder.create',
    resourceType: 'folder',
    resourceId: 'folder-1',
    resourceLabel: 'Legal Contracts 2024',
    ip: '127.0.0.1',
    location: 'Local',
    severity: 'success',
  },
  {
    id: 'audit-8',
    timestamp: days(3),
    ...user('user-maria-rodriguez'),
    action: 'Created Version v1.2',
    actionType: 'document.version',
    resourceType: 'document',
    resourceId: 'doc-2',
    resourceLabel: 'Employment_Contract_Draft.docx',
    ip: '192.168.1.90',
    location: 'Austin, US',
    severity: 'success',
    metadata: { version: '1.2' },
  },
  {
    id: 'audit-9',
    timestamp: days(4),
    userId: 'system',
    userName: 'System Automator',
    userInitials: 'SA',
    userAvatarColor: '#6b7280',
    action: 'Security Policy Change',
    actionType: 'security.policy',
    resourceType: 'system',
    resourceId: 'policy-encryption',
    resourceLabel: 'Encryption Policy',
    ip: '10.0.0.1',
    location: 'Data Center',
    severity: 'critical',
  },
  {
    id: 'audit-10',
    timestamp: days(5),
    ...user('user-sarah-chen'),
    action: 'Upload Denied',
    actionType: 'document.upload_denied',
    resourceType: 'document',
    resourceId: 'denied',
    resourceLabel: 'Restricted_File.zip',
    ip: '192.168.1.55',
    location: 'Boston, US',
    severity: 'warning',
    metadata: { reason: 'permission_denied' },
  },
  {
    id: 'audit-11',
    timestamp: days(6),
    ...user('user-james-doe'),
    action: 'New Upload',
    actionType: 'document.upload',
    resourceType: 'document',
    resourceId: 'doc-4',
    resourceLabel: 'Quarterly_Financial_Statement.pdf',
    ip: '192.168.1.45',
    location: 'London, UK',
    severity: 'success',
  },
  {
    id: 'audit-12',
    timestamp: days(7),
    ...user('user-admin'),
    action: 'Permission Update',
    actionType: 'permission.update',
    resourceType: 'role',
    resourceId: 'role-viewer',
    resourceLabel: 'Viewer Role',
    ip: '127.0.0.1',
    location: 'Local',
    severity: 'warning',
  },
];
